### ISSUE TITLE
Not able to run the examples

### ISSUE THREAD

**Issue by ubwingslab** [nschaetti/EchoTorch#11]
Hi Nils, 
I just installed EchoTorch and tried to run one of the examples provided by EchoTorch. 
After running: python validation_10cv.py, it raised the following errors. It is the same on Windows and Ubuntu. Thanks. 

Traceback (most recent call last):
  File "validation_10cv.py", line 25, in <module>
    from echotorch import datasets
  File "C:\Users\guan\AppData\Local\Continuum\anaconda3\lib\site-packages\echotorch\__init__.py", line 5, in <module>
    import datasets
ModuleNotFoundError: No module named 'datasets'

**Comment by BruceBinBoxing** [comment]
I have the same problem @ubwingslab have you solved it?

**Comment by nschaetti** [comment]
Hi,

The 10CV example is obsolete as I transfered the ReutersC50Dataset class to TorchLanguage. However, I fixed some import errors and tested importing the dataset module and it worked. 
Which version of Python do you use ?

Regards,

Nils

**Comment by ubwingslab** [comment]
> Hi,
> 
> The 10CV example is obsolete as I transfered the ReutersC50Dataset class to TorchLanguage. However, I fixed some import errors and tested importing the dataset module and it worked.
> Which version of Python do you use ?
> 
> Regards,
> 
> Nils
Thank you very much Nils!
