### ISSUE TITLE
narma10_esn.py Empty Exception

### ISSUE THREAD

**Issue by roumpakis** [nschaetti/EchoTorch#18]
I am trying to run  https://github.com/nschaetti/EchoTorch/blob/master/examples/timeserie_prediction/narma10_esn.py but i get an Empty Exception when the example try to load data

data = self._data_queue.get(timeout=timeout)

Why does this happen?
My setup:
 pyTorch 1.5
torchVision 0.6.0
MDP 3.6

**Comment by imhithanks** [comment]
Me too. I can't import Echotorch.

**Comment by dimitrisdermanis** [comment]
see here: https://github.com/nschaetti/EchoTorch/issues/19#issuecomment-759498191

in brief:

1. go to https://github.com/nschaetti/EchoTorch/releases and download the latest release
2. install the latest release from the downloaded file (202006291 is the latest version at the moment): 
`$pip install ./EchoTorch-202006291.zip `
3. test it out using narma10_esn.py (other examples have some issues)
