### ISSUE TITLE
Timeserie data prediction

### ISSUE THREAD

**Issue by JingliangGao** [nschaetti/EchoTorch#8]
Hi,
I recently want to predict chaotic timeserie data and referred to your code **mackey_glass_esn.py**.
Unfortunately, I have met some bugs.
Firstly, this code can't find EchoTorch.datasets.MackeyGlassDataset . Obviously, it is the location problem 
and I just change "EchoTorch" to  "echotorch" to use MackeyGlassDataset which is in my python3.5 's packages(/usr/local/lib/python3.5/dist-packages/EchoTorch-0.1.2-py3.5.egg/echotorch/datasets/MackeyGlassDataset.py).

Next, I ran this code . 
*******************************************************************************************************
Traceback (most recent call last):
  File "mackey_glass_esn.py", line 89, in <module>
    next_hidden = esn(inputs[pos], hidden)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/EchoTorch-0.1.2-py3.5.egg/echotorch/nn/ESNCell.py", line 110, in forward
    time_length = int(u.size()[1])
IndexError: tuple index out of range
******************************************************************************************************* 
It seems that in **mackey_glass_esn.py** line 89 ,the input value **inputs[pos]** is a single float number and its' size is 1, so tuple index out of range, I guess.

Could you give me a hand to solve the problem? Thanks :)

**Comment by nschaetti** [comment]
Hi,

Sorry the Mackey Glass example was an old code using SGD instead of LMS. I updated mackey_glass_esn.py so it is working. I still have to check that the parameters is correctly because the NRMSE is really not that good.

Regards,

Nils
